@startuml 業務処理簿
[*] -> 業務処理簿一覧: 業務処理簿一覧メニュー

業務処理簿一覧 --> 業務処理簿表示: 業務処理簿リスト
業務処理簿表示 --> 業務処理簿一覧: 削除／戻るボタン

業務処理簿一覧 --> 業務処理簿作成: 新規作成ボタン
業務処理簿作成 --> 業務処理簿一覧: 作成／戻るボタン

業務処理簿表示 --> 業務処理簿編集: 編集ボタン
業務処理簿編集 --> 業務処理簿表示: 変更／戻るボタン

業務処理簿一覧 --> 業務処理簿一覧: F/R/S/P

業務処理簿一覧: activity_reports
業務処理簿表示: activity_reports/show
業務処理簿作成: activity_reports/new
業務処理簿編集: activity_reports/edit
@enduml
