@startuml 業務日報
[*] -> 業務日報一覧: 業務日報一覧メニュー

業務日報一覧 --> 対象日選択: 予定から作成ボタン
対象日選択 --> 業務日報一覧: 作成／戻るボタン

業務日報一覧 --> 業務日報表示: 業務日報リスト
業務日報表示 --> 業務日報一覧: 削除／戻るボタン

業務日報一覧 --> 業務日報作成: 新規作成ボタン
業務日報作成 --> 業務日報一覧: 作成／戻るボタン

業務日報表示 --> 業務日報明細表示: 業務日報明細リスト
業務日報明細表示 --> 業務日報表示: 削除／戻るボタン

業務日報表示 --> 業務日報明細作成: 明細追加ボタン
業務日報明細作成 --> 業務日報表示: 作成／戻るボタン

業務日報表示 --> 業務日報編集: 編集ボタン
業務日報編集 --> 業務日報表示: 変更／戻るボタン

業務日報一覧 --> 業務日報一覧: F/R/S/P
業務日報表示 --> 業務日報表示: F/R/S/P

[*] -> 業務日報明細一覧: 業務日報明細一覧メニュー

業務日報明細一覧 --> 業務日報明細表示: 業務日報明細リスト
業務日報明細表示 --> 業務日報明細一覧: 削除／戻るボタン

業務日報明細表示 --> 業務日報明細編集: 編集ボタン
業務日報明細編集 --> 業務日報明細表示: 変更／戻るボタン

業務日報明細一覧 --> 業務日報明細作成: 新規作成ボタン
業務日報明細作成 --> 業務日報明細一覧: 作成／戻るボタン

業務日報明細一覧 --> 業務日報明細一覧: F/R/S/P

業務日報一覧: daily_report_heads
対象日選択: daily_report_heads/date
業務日報表示: daily_report_head/show
業務日報作成: daily_report_heads/new
業務日報編集: daily_report_heads/edit
業務日報明細一覧: daily_report_bodies
業務日報明細表示: daily_report_bodies/show
業務日報明細編集: daily_report_bodies/edit
業務日報明細作成: daily_report_bodies/new

note "F/R/S/P: Filter/Reset/Sort/Pager" as Note1
@enduml
