@startuml 目標管理
[*]--> 目標一覧: 目標一覧メニュー

目標一覧 --> 目標表示: 目標リスト
目標表示 --> 目標一覧: 削除／戻るボタン

目標一覧 --> 目標作成: 新規作成ボタン
目標作成 --> 目標一覧: 作成／戻るボタン

目標表示 --> 目標編集: 編集ボタン
目標編集 --> 目標表示: 変更／戻るボタン

目標一覧 --> 目標一覧: F/R/S/P

目標一覧: milestones
目標表示: milestones/show
目標作成: milestones/new
目標編集: milestones/edit

[*] --> 全体進捗状況: 全体進捗状況メニュー

全体進捗状況 --> 個社別進捗状況: 個社別進捗状況リスト
個社別進捗状況 --> 全体進捗状況: 戻るボタン

全体進捗状況 --> 全体進捗状況: F/R/S/P
個社別進捗状況 --> 個社別進捗状況: F/R/S/P

全体進捗状況: all_progresses
個社別進捗状況: individual_progresses
@enduml