@startuml ナビゲーション
hide empty description
[*] --> ホーム
[*] --> 業務日報
業務日報: ・業務日報一覧\n・業務日報明細一覧
[*] --> 業務処理簿
[*] --> ビジネスマッチング
ビジネスマッチング: ・依頼一覧\n・応募一覧\n・取引一覧
[*] --> 目標管理
目標管理: ・目標一覧\n・全体進捗状況
[*] --> 設定
設定: ・関与先一覧\n・税理士一覧\n・システム管理
[*] --> サインアウト
@enduml
