@startuml 設定
[*] --> 関与先一覧: 関与先一覧メニュー

関与先一覧 --> 関与先表示: 関与先リスト
関与先表示 --> 関与先一覧: 削除／戻るボタン

関与先一覧 --> 関与先作成: 新規作成ボタン
関与先作成 --> 関与先一覧: 作成／戻るボタン

関与先表示 --> 関与先編集: 編集ボタン
関与先編集 --> 関与先表示: 変更／戻るボタン

関与先一覧 --> 関与先一覧: F/R/S/P

関与先一覧: master_companies
関与先表示: master_companies/show
関与先作成: master_companies/new
関与先編集: master_companies/edit

[*] --> 税理士一覧: 税理士一覧メニュー

税理士一覧 --> 税理士表示: 税理士リスト
税理士表示 --> 税理士一覧: 削除／戻るボタン

税理士一覧 --> 税理士作成: 新規作成ボタン
税理士作成 --> 税理士一覧: 作成／戻るボタン

税理士表示 --> 税理士編集: 編集ボタン
税理士編集 --> 税理士表示: 変更／戻るボタン

税理士一覧 --> 税理士一覧: F/R/S/P

税理士一覧: master_taxaccountants
税理士表示: master_taxaccountants/show
税理士作成: master_taxaccountants/new
税理士編集: master_taxaccountants/edit

[*] -> システム管理: システム管理メニュー

システム管理: admin
@enduml
